
package Form;
import java.awt.Color;
import Config.KoneksiSmartHome;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DashboardJFrameSmartHome extends javax.swing.JFrame {

    Connection conn;
    public String kamar, depan, belakang;
    
    public DashboardJFrameSmartHome() {
        conn = KoneksiSmartHome.getConnection();
        initComponents();
        getData();
    }
    
    private void getData(){
        try {
            String sql = "select * from tbl_smart_home order by id desc limit 1";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            rs.next();
            depan = rs.getString("lampu_depan");
            kamar = rs.getString("lampu_kamar");
            belakang = rs.getString("lampu_belakang");
            System.out.println(depan+" | "+kamar+" | "+belakang);
            
            if (depan.equals("1")) {
                jButtonDepan.setBackground(Color.red);
            } else {
                jButtonDepan.setBackground(Color.GRAY);
            }
            if (kamar.equals("1")) {
                jButtonKamar.setBackground(Color.yellow);
            } else {
                jButtonKamar.setBackground(Color.GRAY);
            }
            if (belakang.equals("1")) {
                jButtonBelakang.setBackground(Color.green);
            } else {
                jButtonBelakang.setBackground(Color.GRAY);
            }
            
            rs.close();
            st.close();
        }catch (Exception e){
             Logger.getLogger(DashboardJFrameSmartHome.class.getName()).log(Level.SEVERE, "", e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonDepan = new javax.swing.JButton();
        jButtonKamar = new javax.swing.JButton();
        jButtonBelakang = new javax.swing.JButton();
        jButtonData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("SMART HOME");

        jButtonDepan.setText("LAMPU DEPAN");
        jButtonDepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepanActionPerformed(evt);
            }
        });

        jButtonKamar.setText("LAMPU KAMAR");
        jButtonKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKamarActionPerformed(evt);
            }
        });

        jButtonBelakang.setText("LAMPU BELAKANG");
        jButtonBelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBelakangActionPerformed(evt);
            }
        });

        jButtonData.setText("Data");
        jButtonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonBelakang, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonData)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBelakang, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDepan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButtonData)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataActionPerformed
    DataJFrameSmartHome n = new DataJFrameSmartHome();
        this.setVisible(false);
        DataJFrameSmartHome dataJFrame = new DataJFrameSmartHome();
        dataJFrame.pack();
        dataJFrame.setLocationRelativeTo(null);
        dataJFrame.setVisible(true);
    }//GEN-LAST:event_jButtonDataActionPerformed

    private void jButtonDepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepanActionPerformed
        String messages;
        if (depan.equals("0")) {
            jButtonDepan.setBackground(Color.red);
            depan = "1";
            messages = "Lampu Depan ON";
        } else {
            jButtonDepan.setBackground(Color.GRAY);
            depan = "0";
            messages = "Lampu Depan OFF";
        }
        runLampMySQL(messages);
    }//GEN-LAST:event_jButtonDepanActionPerformed

    private void jButtonKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKamarActionPerformed
        String messages;
        if (kamar.equals("0")) {
            jButtonKamar.setBackground(Color.yellow);
            kamar = "1";
            messages = "Lampu Kamar ON";
        } else {
            jButtonKamar.setBackground(Color.GRAY);
            kamar = "0";
            messages = "Lampu Kamar OFF";
        }
        runLampMySQL(messages);
    }//GEN-LAST:event_jButtonKamarActionPerformed

    private void jButtonBelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBelakangActionPerformed
         String messages;
        if (belakang.equals("0")) {
            jButtonBelakang.setBackground(Color.green);
            belakang = "1";
            messages = "Lampu Belakang ON";
        } else {
            jButtonBelakang.setBackground(Color.GRAY);
            belakang = "0";
            messages = "Lampu Belakang OFF";
        }
        runLampMySQL(messages);
    }//GEN-LAST:event_jButtonBelakangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrameSmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrameSmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrameSmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardJFrameSmartHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardJFrameSmartHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBelakang;
    private javax.swing.JButton jButtonData;
    private javax.swing.JButton jButtonDepan;
    private javax.swing.JButton jButtonKamar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void runLampMySQL(String messages) {
        try {
            String sql = "Insert into tbl_smart_home values (null,?,?,?,now())";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, kamar);
            st.setString(2, depan);
            st.setString(3, belakang);

            int rowInserted = st.executeUpdate();
            if (rowInserted > 0) {
                JOptionPane.showMessageDialog(this, messages);
                getData(); 
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Menambahkan Data", "Error", JOptionPane.ERROR_MESSAGE);
            }

            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
